### ISSUE TITLE
Invalid line in bobross.txt

### ISSUE THREAD

**Issue by EhsanKia** [dekuNukem/Bob_Ross_Twitch_Chatlog_2015#1]
Not sure how this little fella made it in there, but on line 2549939 of bobross.txt, there's:

`:tmi.twitch.tv 001 twitch_plays_3ds :Welcome, GLHF!`

Which clearly doesn't match the "{DATE} {USER}: {MSG}" format.
Just thought I'd let you know.

**Comment by dekuNukem** [comment]
Thanks for noticing. I have no idea how did it get there, I wrote my own logging script so might be a bug somewhere in there. I removed that line and reuploaded it.
